### ISSUE TITLE
can`t sign in

### ISSUE THREAD

**Issue by yeahse** [planetscale/beam#70]
I set .env file well as github_setup.md says

but it showed up below

→ 11     const account = await p.account.findUnique(
  The table `(not available)` does not exist in the current database. {
  message: '\n' +
    'Invalid `p.account.findUnique()` invocation in\n' +
    'C:\\planet\\beam-main\\beam-main\\node_modules\\@next-auth\\prisma-adapter\\dist\\index.js:11:45\n' +
    '\n' +
    '   8 getUserByEmail: (email) => p.user.findUnique({ where: { email } }),\n' +
    '   9 async getUserByAccount(provider_providerAccountId) {\n' +
    '  10     var _a;\n' +
    '→ 11     const account = await p.account.findUnique(\n' +
    '  The table `(not available)` does not exist in the current database.',
  stack: 'Error: \n' +
    'Invalid `p.account.findUnique()` invocation in\n' +
    'C:\\planet\\beam-main\\beam-main\\node_modules\\@next-auth\\prisma-adapter\\dist\\index.js:11:45\n' +
    '\n' +
    '   8 getUserByEmail: (email) => p.user.findUnique({ where: { email } }),\n' +
    '   9 async getUserByAccount(provider_providerAccountId) {\n' +
    '  10     var _a;\n' +
    '→ 11     const account = await p.account.findUnique(\n' +
    '  The table `(not available)` does not exist in the current database.\n' +
    '    at cb (C:\\planet\\beam-main\\beam-main\\node_modules\\@prisma\\client\\runtime\\index.js:38703:17)\n' +
    '    at async PrismaClient._request (C:\\planet\\beam-main\\beam-main\\node_modules\\@prisma\\client\\runtime\\index.js:40853:18)\n' +
    '    at async getUserByAccount (C:\\planet\\beam-main\\beam-main\\node_modules\\@next-auth\\prisma-adapter\\dist\\index.js:11:29)',
  name: 'Error'
}
[next-auth][error][OAUTH_CALLBACK_HANDLER_ERROR] 
https://next-auth.js.org/errors#oauth_callback_handler_error
Invalid `p.account.findUnique()` invocation in
C:\planet\beam-main\beam-main\node_modules\@next-auth\prisma-adapter\dist\index.js:11:45

   8 getUserByEmail: (email) => p.user.findUnique({ where: { email } }),
   9 async getUserByAccount(provider_providerAccountId) {
  10     var _a;
→ 11     const account = await p.account.findUnique(
  The table `(not available)` does not exist in the current database. Error:
Invalid `p.account.findUnique()` invocation in
C:\planet\beam-main\beam-main\node_modules\@next-auth\prisma-adapter\dist\index.js:11:45

   8 getUserByEmail: (email) => p.user.findUnique({ where: { email } }),
   9 async getUserByAccount(provider_providerAccountId) {
  10     var _a;
→ 11     const account = await p.account.findUnique(
  The table `(not available)` does not exist in the current database.
    at cb (C:\planet\beam-main\beam-main\node_modules\@prisma\client\runtime\index.js:38703:17)
    at async PrismaClient._request (C:\planet\beam-main\beam-main\node_modules\@prisma\client\runtime\index.js:40853:18)
    at async getUserByAccount (C:\planet\beam-main\beam-main\node_modules\@next-auth\prisma-adapter\dist\index.js:11:29) {
  name: 'GetUserByAccountError',
  code: 'P2021'
}

**Comment by yeahse** [comment]
done
